name: Autograding Tests
'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: ColaTest
        id: colatest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: ColaTest
          setup-command: ""
          command: mvn -B -Dtest=ColaTest test
          timeout: 10
          max-score: 50

      - name: PilaTest
        id: pilatest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: PilaTest
          setup-command: ""
          command: mvn -B -Dtest=PilaTest test
          timeout: 10
          max-score: 50

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          COLATEST_RESULTS: "${{ steps.colatest.outputs.result }}"
          PILATEST_RESULTS: "${{ steps.pilatest.outputs.result }}"
        with:
          runners: colatest,pilatest